### ISSUE TITLE
add support for one big warc file

### ISSUE THREAD

**Issue by uzerus** [N0taN3rd/Squidwarc#21]
when crawling lot of pages, whole domains... there will be millions of urls, and millions of files, warc files.

there should be support for crawling all to one warc file with fixed size, configurable in config json file.

**Comment by atomicwrites** [comment]
This and deduplicating resources would be great. now, if i archive 300 pages from a site, all the standard assets like logo, js, style-sheets, etc. are saved to disc 300 times. Warc lets you use pointers to another record in the file to avoid this. Also, tools like WebRecoreder Player let you navigate only within a single warc. a temporary sollution would be to catenate them all togeter but this is very wastefull of space.

**Comment by N0taN3rd** [comment]
If @uzerus or @atomicwrites would like to take this issue (work off dev branch), the change is should be simple.

Ensure the appending argument (boolean) read from the config file 
https://github.com/N0taN3rd/Squidwarc/blob/c23780cb092e0d8e0bd39c5df66e0164aa2b51a9/lib/runners/configRunner.js#L29-L35

Is passed to
https://github.com/N0taN3rd/Squidwarc/blob/c23780cb092e0d8e0bd39c5df66e0164aa2b51a9/lib/runners/configRunner.js#L126
https://github.com/N0taN3rd/Squidwarc/blob/c23780cb092e0d8e0bd39c5df66e0164aa2b51a9/lib/runners/configRunner.js#L139

Because initWARC and [node-warc](https://github.com/N0taN3rd/node-warc/blob/65d40be68e42f6f69ef8dc4a781682f203cd8e5b/lib/writers/warcWriterBase.js#L48-L60) is already setup for this....
https://github.com/N0taN3rd/Squidwarc/blob/c23780cb092e0d8e0bd39c5df66e0164aa2b51a9/lib/crawler/index.js#L168-L170

Thank you @atomicwrites for the duplicate, I should have exposed this sooner....

**Comment by peterk** [comment]
This would be a valuable feature. Would it make sense to couple it with better control of how the output WARC is named? And support appending to an existing WARC? (or will that create issues with concurrency?)

**Comment by N0taN3rd** [comment]
appending to warc file is now implemented
