### ISSUE TITLE
Append config seem working not correctly.

### ISSUE THREAD

**Issue by Sian1468** [N0taN3rd/Squidwarc#40]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

Test capture with append config:
```javascript
{
  "use": "puppeteer",
  "headless": true,
  "script": "./userFns.js",
  "mode": "page-all-links",
  "depth": 1,
  "seeds": [
    "https://www.instagram.com/visit_berlin/"
  ],
  "warc": {
    "naming": "url",
   "append": true
  },
  "connect": {
    "launch": true,
    "host": "localhost",
    "port": 9222
  },
  "crawlControl": {
    "globalWait": 60000,
    "inflightIdle": 1000,
    "numInflight": 2,
    "navWait": 8000
  }
}
```
after capture finished ( [logs](https://github.com/N0taN3rd/Squidwarc/files/2666595/logs.txt) ) open result ( [instagram.com_visit_berlin-12-11-2018_1544502298260.zip](https://github.com/N0taN3rd/Squidwarc/files/2666478/instagram.com_visit_berlin-12-11-2018_1544502298260.zip) ) with Webrecorder Player but it show empty warc file:

![webrecorder_player_2018-12-11_11-55-23](https://user-images.githubusercontent.com/45598351/49785711-fcc9da00-fd53-11e8-8881-27315086f095.png)

### What is the expected behavior?
Capture with append config should make correct warc file

### What's your environment?

Windows 10 v1809
node.js v10.14.1
Squidwarc a402335

**Comment by machawk1** [comment]
I tried to replicate this on 1a19eed5a1ea0ab1c8b608c2bffe104c84771184 (latest master), macOS 10.14.2, and node.js v10.12.0.

Using @Sian1468's specified config generated one WARC file (~32.7 MB). Toggling the append attribute generated 67 WARC files (sizes variable from 1.0 MB to 32.2 MB). From this it seems that the "append" functionality is working...at least in the environment I specified above.

I tried to replay @Sian1468's WARC in Webrecorder Player and no Pages are shown. Playing the WARC I created show the "Visit Berlin" memento, as expected.

**Comment by Sian1468** [comment]
Test again with Squidwarc 1a19eed show empty warc on Webrecorder Player 1.6.2

Windows 10 v1809
node.js v10.14.1
[logs](https://github.com/N0taN3rd/Squidwarc/files/2695037/logs.Squidwarc.windows.10.txt)
[instagram.com_visit_berlin-12-19-2018_1545221398723](https://github.com/N0taN3rd/Squidwarc/files/2695041/instagram.com_visit_berlin-12-19-2018_1545221398723.zip)

![webrecorder_player_2018-12-19_19-43-40](https://user-images.githubusercontent.com/45598351/50223805-bf59f200-03ce-11e9-9bab-c07af4e816c6.png)

**Comment by machawk1** [comment]
A little more for bug replication, I repeated the above procedure using @Sian1468 config in the original post using Squidwarc 1a19eed5a1ea0ab1c8b608c2bffe104c84771184, node v10.12.0, macOS 10.14.2 and receive a slightly different yet still unsatisfactory result. A noted difference is that I am executing the config using `./run-crawler.sh -c sian1468.json` instead of `node index.js -c sian1468.json`, though this should not make a difference (I believe).

![screen shot 2018-12-19 at 10 33 18 am](https://user-images.githubusercontent.com/2514780/50230009-ae32c600-0379-11e9-9159-be7416f9ee7e.png)
![screen shot 2018-12-19 at 10 33 21 am](https://user-images.githubusercontent.com/2514780/50230010-ae32c600-0379-11e9-93c3-6ad3ae580b7e.png)
